// Code generated by sgoiter emit go127; DO NOT EDIT.
package tuidiff

type C2_cell_t struct {
	Rune_ uint32
	Fg    byte
	Bg    byte
	Flags byte
	Width byte
}

type C2_span_t struct {
	X      int
	Y      int
	Length int
}

func C2_chunk_dirty4(front []uint64, back []uint64) int {
	var v2 int
	v2 = 0
	if front[0] != back[0] {
		v2++
	}
	if front[1] != back[1] {
		v2 += 2
	}
	if front[2] != back[2] {
		v2 += 4
	}
	if front[3] != back[3] {
		v2 += 8
	}
	return v2
}

func C2_cells_equal_at(front []C2_cell_t, back []C2_cell_t, i int) int {
	v3 := &front[i]
	v5 := &back[i]
	if v3.Rune_ != v5.Rune_ {
		return 0
	}
	v8 := &front[i]
	v10 := &back[i]
	if v8.Fg != v10.Fg {
		return 0
	}
	v13 := &front[i]
	v15 := &back[i]
	if v13.Bg != v15.Bg {
		return 0
	}
	v18 := &front[i]
	v20 := &back[i]
	if v18.Flags != v20.Flags {
		return 0
	}
	v23 := &front[i]
	v25 := &back[i]
	if v23.Width != v25.Width {
		return 0
	}
	return 1
}

func C2_diff_grid_scalar(front []C2_cell_t, back []C2_cell_t, count int, stride int, width int, spans []C2_span_t, max_spans int) int {
	var v7 int
	var v9 int
	var v11 int
	var v13 int
	var v15 int
	var v17 int
	var v19 int
	var v25 int
	var v27 int
	var v28 int
	var v31 *C2_span_t
	var v40 *C2_cell_t
	var v42 *C2_cell_t
	var v45 *C2_cell_t
	var v47 *C2_cell_t
	var v50 *C2_cell_t
	var v52 *C2_cell_t
	var v55 *C2_cell_t
	var v57 *C2_cell_t
	var v60 *C2_cell_t
	var v62 *C2_cell_t
	var v67 int
	var v69 int
	var v70 int
	var v73 *C2_span_t
	var v80 *C2_span_t
	var v88 *C2_span_t
	_ = 0
	v7 = 0
	v9 = 0
	v11 = 0
	v13 = 0
	v15 = 0
	v17 = 0
	if width <= 0 {
		width = stride
	}
	for v19 = 0; v19 < count; v19++ {
		v25 = v19 % stride
		v27 = v19 / stride
		if v25 >= width {
			if v9 != 0 {
				if v7 < max_spans {
					v31 = &spans[v7]
					v31.X = v11
					v31.Y = v13
					v31.Length = v15
					v7++
				} else {
					v17 = 1
				}
				v9 = 0
				v15 = 0
			}
		} else {
			v28 = 0
			v40 = &front[v19]
			v42 = &back[v19]
			if v40.Rune_ != v42.Rune_ {
				v28 = 1
			} else {
				v45 = &front[v19]
				v47 = &back[v19]
				if v45.Fg != v47.Fg {
					v28 = 1
				} else {
					v50 = &front[v19]
					v52 = &back[v19]
					if v50.Bg != v52.Bg {
						v28 = 1
					} else {
						v55 = &front[v19]
						v57 = &back[v19]
						if v55.Flags != v57.Flags {
							v28 = 1
						} else {
							v60 = &front[v19]
							v62 = &back[v19]
							if v60.Width != v62.Width {
								v28 = 1
							}
						}
					}
				}
			}
			if v28 != 0 {
				if v9 == 0 {
					v9 = 1
					v11 = v25
					v13 = v27
					v15 = 1
				} else {
					v67 = func() int {
						if v27 == v13 {
							return 1
						}
						return 0
					}()
					v69 = func() int {
						if v25 == (v11 + v15) {
							return 1
						}
						return 0
					}()
					v70 = func() int {
						if (v67 != 0) && (v69 != 0) {
							return 1
						}
						return 0
					}()
					if v70 != 0 {
						v15++
					} else {
						if v7 < max_spans {
							v73 = &spans[v7]
							v73.X = v11
							v73.Y = v13
							v73.Length = v15
							v7++
						} else {
							v17 = 1
						}
						v11 = v25
						v13 = v27
						v15 = 1
					}
				}
			} else {
				if v9 != 0 {
					if v7 < max_spans {
						v80 = &spans[v7]
						v80.X = v11
						v80.Y = v13
						v80.Length = v15
						v7++
					} else {
						v17 = 1
					}
					v9 = 0
					v15 = 0
				}
			}
		}
	}
	if v9 != 0 {
		if v7 < max_spans {
			v88 = &spans[v7]
			v88.X = v11
			v88.Y = v13
			v88.Length = v15
			v7++
		} else {
			v17 = 1
		}
	}
	if v17 != 0 {
		return -1
	}
	return v7
}
