// Code generated by sgoiter emit go127; DO NOT EDIT.
package vtparser

type C2_cell_t struct {
	Rune_ uint32
	Fg    byte
	Bg    byte
	Flags byte
	Width byte
}

type C2_vt_parser_t struct {
	State        int
	Cursor_x     int
	Cursor_y     int
	Cur_fg       int
	Cur_bg       int
	Cur_attr     int
	Width        int
	Height       int
	Prm          int
	Nparams      int
	Params       [4]int
	Pending_utf8 [4]byte
	Pending_len  int
}

func C2_grid_clear(cells []C2_cell_t, n int, fg byte, bg byte) {
	if n <= 0 {
		return
	}
	_cells := cells[:n]
	_cells[0] = C2_cell_t{Rune_: 32, Fg: fg, Bg: bg, Flags: 0, Width: 1}
	for copied := 1; copied < n; {
		copied += copy(_cells[copied:], _cells[:copied])
	}
}

func C2_grid_clear_row(cells []C2_cell_t, y int, stride int, width int, fg byte, bg byte) {
	var v6 int
	var v15 *C2_cell_t
	for v6 = 0; v6 < width; v6++ {
		v15 = &cells[int((y*stride)+v6)]
		v15.Rune_ = 32
		v15.Fg = fg
		v15.Bg = bg
		v15.Flags = 0
		v15.Width = 1
	}
}

func C2_grid_scroll_up(cells []C2_cell_t, width int, height int, stride int, nlines int) {
	var v5 int
	if nlines < 1 {
		return
	}
	if nlines > height {
		nlines = height
	}
	v12 := height - nlines
	if stride == width {
		move := v12 * stride
		src := nlines * stride
		copy(cells[:move], cells[src:src+move])
	} else {
		for v5 = 0; v5 < v12; v5++ {
			dst := v5 * stride
			src := (v5 + nlines) * stride
			copy(cells[dst:dst+width], cells[src:src+width])
		}
	}
	if stride == width {
		move := v12 * stride
		C2_grid_clear(cells[move:], (height-v12)*stride, byte(0), byte(0))
	} else {
		for v5 = v12; v5 < height; v5++ {
			C2_grid_clear_row(cells[:], v5, stride, width, byte(0), byte(0))
		}
	}
}

func C2_vt_init(p *C2_vt_parser_t, width int, height int) {
	p.State = 0
	p.Cursor_x = 0
	p.Cursor_y = 0
	p.Cur_fg = 0
	p.Cur_bg = 0
	p.Cur_attr = 0
	p.Width = width
	p.Height = height
	p.Prm = 0
	p.Nparams = 0
	p.Pending_len = 0
}

func C2_vt_put(p *C2_vt_parser_t, cells []C2_cell_t, r uint32) {
	var v3 int
	var v5 int
	_ = 0
	v3 = p.Width
	v5 = p.Height

	if (v3 <= 0) || (v5 <= 0) {
		return
	}
	if p.Cursor_x >= v3 {
		p.Cursor_x = 0
		p.Cursor_y++
	}
	if p.Cursor_y >= v5 {
		p.Cursor_y = v5 - 1
	}
	v27 := &cells[int((p.Cursor_y*v3)+p.Cursor_x)]
	v27.Rune_ = r
	v27.Fg = byte(p.Cur_fg)
	v27.Bg = byte(p.Cur_bg)
	v27.Flags = byte(p.Cur_attr)
	v27.Width = 1
	p.Cursor_x++
}

func C2_vt_add_digit(p *C2_vt_parser_t, b byte) {
	var v2 int
	var v6 int
	v2 = int(b)
	v2 -= 48
	v6 = p.Prm
	v6 *= 10
	v6 += v2
	if v6 > 0x270f {
		v6 = 0x270f
	}
	p.Prm = v6
}

func C2_vt_finish_prm(p *C2_vt_parser_t) {
	_ = 0
	if p.Nparams < 4 {
		p.Params[p.Nparams] = p.Prm
		p.Nparams++
	}
	p.Prm = 0
}

func C2_vt_param(p *C2_vt_parser_t, i int, def int) int {
	_ = 0
	if i < p.Nparams {
		if p.Params[i] != 0 {
			return p.Params[i]
		}
	}
	return def
}

func C2_vt_sgr(p *C2_vt_parser_t) {
	var v1 int
	var v10 int
	_ = 0
	for v1 = 0; v1 < p.Nparams; v1++ {
		v10 = p.Params[v1]
		if v10 == 0 {
			p.Cur_fg = 0
			p.Cur_bg = 0
			p.Cur_attr = 0
		}
		if v10 == 1 {
			p.Cur_attr |= 1
		}
		if v10 == 4 {
			p.Cur_attr |= 4
		}
		if v10 == 7 {
			p.Cur_attr |= 8
		}

		if (v10 >= 30) && (v10 <= 37) {
			p.Cur_fg = v10 - 30
		}

		if (v10 >= 40) && (v10 <= 47) {
			p.Cur_bg = v10 - 40
		}
	}
}

func C2_vt_clear_span(cells []C2_cell_t, i0 int, i1 int, fg byte, bg byte) {
	var v11 *C2_cell_t
	for i0 < i1 {
		v11 = &cells[i0]
		v11.Rune_ = 32
		v11.Fg = fg
		v11.Bg = bg
		v11.Flags = 0
		v11.Width = 1
		i0++
	}
}

func C2_vt_csi(p *C2_vt_parser_t, cells []C2_cell_t, b byte) {
	var v3 int
	var v4 int
	var v5 int
	var v6 int
	var v22 int
	_ = 0
	C2_vt_finish_prm(p)
	v4 = p.Width
	v5 = p.Height

	if (b == 'H') || (b == 'f') {
		v22 = C2_vt_param(p, 1, 1)
		p.Cursor_y = C2_vt_param(p, 0, 1) - 1
		p.Cursor_x = v22 - 1
		if p.Cursor_y < 0 {
			p.Cursor_y = 0
		}
		if p.Cursor_x < 0 {
			p.Cursor_x = 0
		}

		if (p.Height > 0) && (p.Cursor_y >= p.Height) {
			p.Cursor_y = p.Height - 1
		}

		if (p.Width > 0) && (p.Cursor_x >= p.Width) {
			p.Cursor_x = p.Width - 1
		}
	}
	if b == 'A' {
		v3 = C2_vt_param(p, 0, 1)
		p.Cursor_y -= v3
		if p.Cursor_y < 0 {
			p.Cursor_y = 0
		}
	}
	if b == 'B' {
		v3 = C2_vt_param(p, 0, 1)
		p.Cursor_y += v3

		if (p.Height > 0) && (p.Cursor_y >= p.Height) {
			p.Cursor_y = p.Height - 1
		}
	}
	if b == 'C' {
		v3 = C2_vt_param(p, 0, 1)
		p.Cursor_x += v3

		if (p.Width > 0) && (p.Cursor_x >= p.Width) {
			p.Cursor_x = p.Width - 1
		}
	}
	if b == 'D' {
		v3 = C2_vt_param(p, 0, 1)
		p.Cursor_x -= v3
		if p.Cursor_x < 0 {
			p.Cursor_x = 0
		}
	}
	if b == 'm' {
		C2_vt_sgr(p)
	}
	if b == 'J' {
		v3 = C2_vt_param(p, 0, 0)
		v6 = (p.Cursor_y * v4) + p.Cursor_x
		if v3 == 0 {
			C2_vt_clear_span(cells[:], v6, (v4 * v5), byte(p.Cur_fg), byte(p.Cur_bg))
		}
		if v3 == 1 {
			C2_vt_clear_span(cells[:], 0, (v6 + 1), byte(p.Cur_fg), byte(p.Cur_bg))
		}
		if v3 == 2 {
			C2_vt_clear_span(cells[:], 0, (v4 * v5), byte(p.Cur_fg), byte(p.Cur_bg))
		}
	}
	if b == 'K' {
		v3 = C2_vt_param(p, 0, 0)
		v6 = p.Cursor_y * v4
		if v3 == 0 {
			C2_vt_clear_span(cells[:], (v6 + p.Cursor_x), (v6 + v4), byte(p.Cur_fg), byte(p.Cur_bg))
		}
		if v3 == 1 {
			C2_vt_clear_span(cells[:], v6, ((v6 + p.Cursor_x) + 1), byte(p.Cur_fg), byte(p.Cur_bg))
		}
		if v3 == 2 {
			C2_vt_clear_span(cells[:], v6, (v6 + v4), byte(p.Cur_fg), byte(p.Cur_bg))
		}
	}
	p.State = 0
}

func C2_vt_feed_byte(p *C2_vt_parser_t, cells []C2_cell_t, b byte) int {
	var v10 *C2_cell_t
	_ = 0
	if p.Height < 0 {
		v10 = &cells[0]
		v10.Rune_ = 0
	}
	switch p.State {
	case 0:
		if b == 27 {
			p.State = 1
			return 0
		}
		if b == 10 {
			p.Cursor_y++
			p.Cursor_x = 0
			return 1
		}
		if b == 13 {
			p.Cursor_x = 0
			return 1
		}

		if (b >= 32) && (b <= 0x7e) {
			C2_vt_put(p, cells[:], uint32(b))
			return 1
		}
	case 1:
		if b == 0x5b {
			p.State = 2
			p.Prm = 0
			p.Nparams = 0
			return 0
		}
		if b == 0x5d {
			p.State = 3
			return 0
		}
		p.State = 0
	case 2:

		if (b >= '0') && (b <= '9') {
			C2_vt_add_digit(p, b)
			return 0
		}
		if b == ';' {
			C2_vt_finish_prm(p)
			return 0
		}

		if (b >= 64) && (b <= 0x7e) {
			C2_vt_csi(p, cells[:], b)
			return 0
		}
	case 3:

		if (b == 7) || (b == 27) {
			p.State = 0
			return 0
		}
	}
	return 0
}
