// Code generated by sgoiter emit go127; DO NOT EDIT.
package myers

const __str_4f9f73b3 = "120000"
const __str_cb0b20f9 = "160000"

func C2_myers_ses(a []int, n int, b []int, m int, v []int, vlen int) int {
	var v36 int
	var v40 int
	var v45 int
	var v48 int
	var v49 int
	var v58 int
	var v59 int
	var v60 int
	var v71 int
	var v85 int
	var v86 int
	var v87 int
	v7 := func() int {
		if n == 0 {
			return 1
		}
		return 0
	}()
	v9 := func() int {
		if m == 0 {
			return 1
		}
		return 0
	}()
	v10 := func() int {
		if (v7 != 0) && (v9 != 0) {
			return 1
		}
		return 0
	}()
	if v10 != 0 {
		return 0
	}
	v13 := func() int {
		if n < 0 {
			return 1
		}
		return 0
	}()
	v15 := func() int {
		if m < 0 {
			return 1
		}
		return 0
	}()
	v16 := func() int {
		if (v13 != 0) || (v15 != 0) {
			return 1
		}
		return 0
	}()
	if v16 != 0 {
		return -1
	}
	v21 := n + m
	v25 := (v21 + v21) + 1
	if v25 > vlen {
		return -1
	}
	{
		_v := v[:v25]
		clear(_v[:v25])
	}
	for v36 = 0; v36 <= v21; v36++ {
		v40 = -v36
		for v40 <= v36 {
			v48 = func() int {
				if v40 == -v36 {
					return 1
				}
				return 0
			}()
			v49 = func() int {
				if v40 != v36 {
					return 1
				}
				return 0
			}()
			v58 = func() int {
				if v[int((v40-1)+v21)] < v[v40+1+v21] {
					return 1
				}
				return 0
			}()
			v59 = func() int {
				if (v49 != 0) && (v58 != 0) {
					return 1
				}
				return 0
			}()
			v60 = func() int {
				if (v48 != 0) || (v59 != 0) {
					return 1
				}
				return 0
			}()
			if v60 != 0 {
				v45 = v[v40+1+v21]
			} else {
				v45 = v[int((v40-1)+v21)] + 1
			}
			v71 = v45 - v40
			for v45 < n && v71 < m && a[v45] == b[v71] {
				v45++
				v71++
			}
			v[v40+v21] = v45
			v85 = func() int {
				if v45 >= n {
					return 1
				}
				return 0
			}()
			v86 = func() int {
				if v71 >= m {
					return 1
				}
				return 0
			}()
			v87 = func() int {
				if (v85 != 0) && (v86 != 0) {
					return 1
				}
				return 0
			}()
			if v87 != 0 {
				return v36
			}
			v40 += 2
		}
	}
	return -1
}

func C2_validate_patch_mode(mode_str []byte) int {
	v1 := uint64(0)
	if mode_str == nil {
		return 1
	}
	v7 := func() int {
		a, b := mode_str[v1:], []byte([]byte(__str_4f9f73b3))
		for i := 0; i < len(a) && i < len(b); i++ {
			if a[i] != b[i] {
				if a[i] < b[i] {
					return -1
				}
				return 1
			}
			if a[i] == 0 {
				return 0
			}
		}
		if len(a) < len(b) && (len(a) == 0 || a[len(a)-1] != 0) {
			return -1
		}
		if len(a) > len(b) && (len(b) == 0 || b[len(b)-1] != 0) {
			return 1
		}
		return 0
	}()
	if v7 == 0 {
		return 0
	}
	v12 := func() int {
		a, b := mode_str[v1:], []byte([]byte(__str_cb0b20f9))
		for i := 0; i < len(a) && i < len(b); i++ {
			if a[i] != b[i] {
				if a[i] < b[i] {
					return -1
				}
				return 1
			}
			if a[i] == 0 {
				return 0
			}
		}
		if len(a) < len(b) && (len(a) == 0 || a[len(a)-1] != 0) {
			return -1
		}
		if len(a) > len(b) && (len(b) == 0 || b[len(b)-1] != 0) {
			return 1
		}
		return 0
	}()
	if v12 == 0 {
		return 0
	}
	return 1
}
